// Builds js/vocab.js: the built-in tag list and folder ideas, with their text
// embeddings pre-computed, so the site only has to download the (small) image
// half of the AI model.
//
// To change the tags or folder ideas, edit the lists below, then:
//   cd tools && npm i @huggingface/transformers@4.3.0 && node build-vocab.mjs
import { AutoTokenizer, CLIPTextModelWithProjection } from '@huggingface/transformers';
import { writeFileSync } from 'node:fs';

const MODEL = 'Xenova/mobileclip_s0';

// [tag, facet, prompt]. Tags are suggested per facet (best match in each).
// An empty tag is a neutral anchor that is never suggested.
const TAGS = [
  ['sketch', 'kind', 'a rough sketch'],
  ['pencil', 'kind', 'a graphite pencil drawing'],
  ['charcoal', 'kind', 'a charcoal drawing'],
  ['ink', 'kind', 'an ink drawing'],
  ['line art', 'kind', 'clean black line art'],
  ['watercolor', 'kind', 'a watercolor painting'],
  ['oil painting', 'kind', 'an oil painting'],
  ['digital art', 'kind', 'digital art'],
  ['pixel art', 'kind', 'pixel art'],
  ['3d render', 'kind', 'a 3d render'],
  ['manga', 'kind', 'a black and white manga page with panels and speech bubbles'],
  ['comic', 'kind', 'a comic strip with panels and speech bubbles'],
  ['storyboard', 'kind', 'a storyboard'],
  ['anime', 'kind', 'an anime style illustration'],
  ['photo', 'kind', 'a photograph'],
  ['screenshot', 'kind', 'a screenshot of a computer or phone screen'],
  ['collage', 'kind', 'a collage'],
  ['poster', 'kind', 'a poster'],
  ['sculpture', 'kind', 'a sculpture'],

  ['portrait', 'subject', 'a portrait of a person'],
  ['figure', 'subject', 'a figure study of a human body'],
  ['character design', 'subject', 'a character design sheet'],
  ['landscape', 'subject', 'a landscape with mountains, sky or fields'],
  ['cityscape', 'subject', 'a city street with buildings'],
  ['architecture', 'subject', 'architecture and buildings'],
  ['interior', 'subject', 'a room interior'],
  ['still life', 'subject', 'a still life of objects on a table'],
  ['nature', 'subject', 'plants, trees and nature'],
  ['animals', 'subject', 'an animal'],
  ['flowers', 'subject', 'flowers'],
  ['food', 'subject', 'food'],
  ['fashion', 'subject', 'fashion and clothing'],
  ['text', 'subject', 'a page of written text'],
  ['logo', 'subject', 'a logo'],
  ['pattern', 'subject', 'a repeating pattern'],
  ['abstract', 'subject', 'abstract art'],

  ['black and white', 'look', 'a black and white image'],
  ['colorful', 'look', 'a vibrant colorful image'],
  ['color palette', 'look', 'color swatches and a color palette'],
  ['', 'look', 'an image'], // neutral anchor: absorbs "nothing special", never suggested
];

// Folder ideas for photos in Unsorted. `match` lists folder names that count
// as the same idea, so an existing "Drawings" folder gets the sketches.
const IDEAS = [
  ['Sketches', 'a pencil or ink sketch', ['sketch', 'sketches', 'drawing', 'drawings', 'doodle', 'doodles', 'studies', 'study']],
  ['Manga', 'a black and white manga page with panels and speech bubbles', ['manga', 'manhwa', 'manhua']],
  ['Comics', 'a comic strip with panels and speech bubbles', ['comic', 'comics', 'webcomic', 'webcomics', 'strips']],
  ['Paintings', 'a painting', ['painting', 'paintings', 'watercolor', 'watercolors', 'oils', 'oil paintings']],
  ['Digital art', 'digital art', ['digital', 'digital art', 'illustration', 'illustrations', 'art']],
  ['Photos', 'a photograph', ['photo', 'photos', 'photography', 'pictures', 'pics']],
  ['Screenshots', 'a screenshot of a screen', ['screenshot', 'screenshots', 'screencaps', 'screens']],
];

const tokenizer = await AutoTokenizer.from_pretrained(MODEL);
const model = await CLIPTextModelWithProjection.from_pretrained(MODEL, { dtype: 'fp32' });
async function embed(texts) {
  const { text_embeds } = await model(tokenizer(texts, { padding: 'max_length', truncation: true }));
  return Buffer.from(new Float32Array(text_embeds.normalize().data).buffer).toString('base64');
}

const out = `// Generated by tools/build-vocab.mjs. Do not edit by hand.
export const MODEL = ${JSON.stringify(MODEL)};
export const TAGS = ${JSON.stringify(TAGS.map(([tag, facet]) => ({ tag, facet })))};
export const IDEAS = ${JSON.stringify(IDEAS.map(([name, , match]) => ({ name, match })))};
export const TAG_VECTORS = ${JSON.stringify(await embed(TAGS.map(t => t[2])))};
export const IDEA_VECTORS = ${JSON.stringify(await embed(IDEAS.map(t => t[1])))};
`;
const target = process.argv[2] || new URL('../js/vocab.js', import.meta.url);
writeFileSync(target, out);
console.log(`wrote ${TAGS.length} tags and ${IDEAS.length} folder ideas to ${target}`);
